sudo: required
services:
  - docker
env:
  global
    - secure: xRvTqcJ+BCWBVBWjTmG87Y3gJ78M2euWjjLUrzkizqQbCjNaWIUydtPbIb8Sr1ttKpnteWIXwtTo/DkWQxnfiEZNkqOfCpiSTQsjv4RxAAnocnYWLc+aTwWEZlwvHJTa7HHqxcD281rKu6g0zZPQOeTL1ZezERBSzAmbX/S+uqEOSddQZvh2kj3jC2AzOrEKnkrO/+7e0JmWhpXGV4/zXscEmxUqiQ1gHiMGMAiFQAvu4DNeMscD5T6SHmQSRR8EuCyGgc3X8MAGl8AevQ682feXQm1arSB4DoUVKpULUKr9gyGY5hQkz7Uxpl77kpddK/8qqz22J2SILLS0E+A5kxZUyKQ6SFtqPpKkNN8zORjLZFZzmO92sjuvawToulE2SfFLHTcHaJIsjRncGc+t9uFAOBXgGIawhkLK7IMUCCGit0wmj6RQHMR0XtRAsJuQveAfaf865CjeKxxObi9FJaLVrp0gkOPI+jJBYrSGoJw0WAOOmCWU7E4f5tRjpy32Das5eRfABgE/PQK1vURqJKBfcSAPGNcDgKHAKknXxsYTHkirN2aOkfXBGGauL0ou2TGmVqfZVmcSlA04ixS5oIgNyH/87NYHFO/Vzbor2H5DnVXQGbfRnx+dZbKxk6MDLkiGxHqbLyuISv17mIG1CN+CXniG48PQhbdOtIpVpW4=:
    - secure: Cu3JYxM6VF1FsC1ivuwhyeFlnJbmeowK+iVsxL6IAA12G1JWqW2YvXaW4FKGJVyt2GUuje6dPqiSxIjpykC8kLnq+BmquBFii82eXlfWqurs7Kr+9KWk/gVk74KeM++mCYKZlYoxnPxDrsBVvKj+Pks7mLzl1cscFCIrdejGohfgB0f14cJI2OfE9JWQ8wlSuTh8zVkQTQdaLojRW+uFfyltFc1Je5T/6V0AR09/OZX9F34mjkskGBUySYut/ORgmNm8VelvxvhjAReAHk3iXOxnnJ48VDvoZT7L2E7Ois1qPwurzQbbkQ3ljefkImgykuiHjNiauC5cc4NFjOiWZNUluvu7PUC/xeBNuR2kqF6Ak8fpCjQUZRaNHYuwTETlXKd7NJtQB+KND4YEezlmOKzbvLpjBGsaB9AgNNzJ8uhcbfzASn/dsKD7r8j6V7iY+pbf6sKaAMWk5QkSA35PF/74lS37lnei4XTXBtiOWux3qfqEtYvIfK9HzxugOLiDDiiu9C6ADPVu3ttdfvNHf+5Wb4sqmPkra3wVmkdVdCIAN4vZ3nfiQ9xN+UeJ2myS0QonhnXXrz7G80jhpftfOkSMNGVQnpL5LVE00XlgHedBzS0t80TXDZSDymJTsNDOsVBwPQ1VtfiXh86028/nLaHMt5H5JeXSS7WeUwB/Pb8=
    - secure: gpow9mEHW8jtzqMkyfIMq8KEHnNGBjEwKz6MFkbWffG2he5mmUtUrreM7MVsQlguhSrgC/qBl+9OuF3cwAq5A3F97QaAT42gqtdU78O5B21XBDVsltiphX0PonzGVxmKWlwUjKTF6CLaz1bXFfpoRPiNbpxGUwK90AnVFmz43J9x/qN3tK8sfPmnj2xDN+UYXOr5Y2PmoX8jWq54ugkVpAu+B5p1VsYmeDqEJTfrLzh8OGwspWvdapBkKjbMlREaRPGO6YiySzYz336UvC9y3WTqRdgGODnxqcIy0F9ggEtx3frcyjwjuOLLSG55jrurB/VjLA7ikcpMXOTyUZCfoIF1k826m2zJUSAxezcLNV+3dzag6UxcrpdZ1cLcoVnMBZEfJzMSRNayAYGLA2voWJszAV8OA+3Jui504Tw7p4wmEpKzPLEHprQW/FSHarHkoRQv/qgYa43pNxoWkL6NY+FUQoqHh1mWjTntDP8QPHBPhkEGbnHDsLYgnO4d6G23ds2IjUqjJCBggnYLAZ4VmkZKEfidXl2xyTYBQy4oLYf599lim98arO4YQ47rU2A49UIlkbiuS1q0CkcahxG2HcFilznZUy7UZClaqJY6ou7RBkX2CdQAJul2MNKq8J+8zoa1MQ2DjNnF1gKrG8xf323zYZtGGtTDxgU8+KTnZh0= 
    - REPO: shazi7804/ubuntu-node-yarn
  matrix:
    - NODE_VERSION: '4.8'  TAG: '4.8'
    - NODE_VERSION: '6.10' TAG: '6.10'
    - NODE_VERSION: '7.10' TAG: '7.10'
script:
  - docker build -t ${REPO}:${NODE_VERSION} ${NODE_VERSION}/.
  - docker run -it ${REPO}:${NODE_VERSION} node -v

after_success:
  - docker images
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker tag $REPO $REPO:$TAG
      docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
      docker push $REPOSITORY;
    fi

notifications:
  email: false
  slack:
    secure: 5mgrA3hInrn3CGdvg1HuItcL27niO4dWswLMZ/1x2fYUea1Z8OyweAuL8mKeuepLUVsvLbll3fXePE477OXJ9TNdxq28bVmv5FaN51Hhdx0WEEcoHlbWeFbG7SRk0ejMb+D3gohIIOGZFzyhFi4s0pG6+IkhEIZCOO9jZa5ZuKZ0arY99jIkXTo9bVi41RNX40cIMfjv0NhrQoMlzxcSRVGRNBx/tWDthaTK/lAnvlIkb2vbQHinUcrvDv6fC5btQ2Uchx/ZLDvFi6s6BZpB+YNzjeq6qyNYqLAUaRvRcBBZkT30nb6ise7xtiFgOvQL4fcVRYVQO2m2GID33mtJ334VP1Og8XgCOslg8vgo1Un32M0mP3Ot7ymuZQlEpn/W2NbXbjMVruZCmeTVzCS7P40jG8CkCbnKl+IMDt70qyqsp2AaQVlpJc8Apz/nFQHXmVSBraCCLiqON1beC6G38N+md8jMaQsyu98SNPiN3HU97WO3D9bqdKMlE0m7rO3G3TdM9E3DIHqNUK9YEMNUn469pWToiSMiWE+hugtR6vIXyrdZzVDuZimVwnOmtAVOEW6rdc9kGcxrgnDTvuervHBskNsF1T6GjLJNc1ZSkSGsXyZoNDlPvpa/QBCs0gfImLB8KT42aW3rb2WbJ+4ZqopAyVjB+Zqiy0ugoPrnw40=
