sudo: required

services:
  - docker

env:
  global :
    - REPOSITORY: shazi7804/ubuntu-node-yarn
  matrix :
    - NODE_VERSION: '4.8'
    - NODE_VERSION: '6.10'
    - NODE_VERSION: '7.10'

script:
  - docker build -t ${REPOSITORY}:${NODE_VERSION}